repos:
  - repo: https://github.com/pycqa/flake8.git
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: |
            (?x)^(
                thirdparty/|
                examples/|
                tests/run.py
            )$
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        exclude: |
            (?x)^(
                examples/|
                tests/run.py|
                swift/cli/sft.py
            )$
  - repo: https://github.com/google/yapf.git
    rev: v0.43.0
    hooks:
      - id: yapf
        exclude: |
            (?x)^(
                thirdparty/|
                examples/|
                tests/run.py
            )$
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: thirdparty/|tests/run.py
      - id: check-yaml
        exclude: thirdparty/|tests/run.py
      - id: end-of-file-fixer
        exclude: thirdparty/|tests/run.py
      - id: requirements-txt-fixer
        exclude: thirdparty/|tests/run.py
      - id: double-quote-string-fixer
        exclude: thirdparty/|tests/run.py
      - id: check-merge-conflict
        exclude: thirdparty/|tests/run.py
      - id: fix-encoding-pragma
        exclude: thirdparty/|tests/run.py
        args: ["--remove"]
      - id: mixed-line-ending
        exclude: thirdparty/|tests/run.py
        args: ["--fix=lf"]
